// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhkCx1D-k58ZVPciEIH6U_YOt7qiLR_7M',
    appId: '1:645233644037:web:cda9621575a76df696826c',
    messagingSenderId: '645233644037',
    projectId: 'phoenix-ccs-hackthon',
    authDomain: 'phoenix-ccs-hackthon.firebaseapp.com',
    storageBucket: 'phoenix-ccs-hackthon.appspot.com',
    measurementId: 'G-G634G7L4Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT_kzY-wuo2W-9Z1px5eufknPiMkcIXh4',
    appId: '1:645233644037:android:336c8c6cb929ae2496826c',
    messagingSenderId: '645233644037',
    projectId: 'phoenix-ccs-hackthon',
    storageBucket: 'phoenix-ccs-hackthon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFAClRJQtF86viZJpDxAuJ2-hvH9XA9v0',
    appId: '1:645233644037:ios:45b541c4ab8781e496826c',
    messagingSenderId: '645233644037',
    projectId: 'phoenix-ccs-hackthon',
    storageBucket: 'phoenix-ccs-hackthon.appspot.com',
    iosClientId: '645233644037-enmevdpqekol3dbt35s36qa1kak6jq9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoenixCcs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFAClRJQtF86viZJpDxAuJ2-hvH9XA9v0',
    appId: '1:645233644037:ios:45b541c4ab8781e496826c',
    messagingSenderId: '645233644037',
    projectId: 'phoenix-ccs-hackthon',
    storageBucket: 'phoenix-ccs-hackthon.appspot.com',
    iosClientId: '645233644037-enmevdpqekol3dbt35s36qa1kak6jq9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoenixCcs',
  );
}
